### ISSUE TITLE
如何在服务端渲染的的情况下使用muse ；现在 我使用时 会报这样的一个错误，请问该怎么解决？

### ISSUE THREAD

**Issue by RainCha** [museui/muse-ui#166]
ReferenceError: Element is not defined
    at Object.<anonymous> (/Users/vinchan/LearnPro/shufeijie_test/node_modules/muse-ui/dist/muse-ui.js:8:27216)
    at t (/Users/vinchan/LearnPro/shufeijie_test/node_modules/muse-ui/dist/muse-ui.js:1:423)
    at Object.e.exports.render.e (/Users/vinchan/LearnPro/shufeijie_test/node_modules/muse-ui/dist/muse-ui.js:9:29405)
    at t (/Users/vinchan/LearnPro/shufeijie_test/node_modules/muse-ui/dist/muse-ui.js:1:423)
    at Object.defineProperty.value (/Users/vinchan/LearnPro/shufeijie_test/node_modules/muse-ui/dist/muse-ui.js:4:13167)
    at t (/Users/vinchan/LearnPro/shufeijie_test/node_modules/muse-ui/dist/muse-ui.js:1:423)
    at Object.e.__esModule.default (/Users/vinchan/LearnPro/shufeijie_test/node_modules/muse-ui/dist/muse-ui.js:6:20522)
    at t (/Users/vinchan/LearnPro/shufeijie_test/node_modules/muse-ui/dist/muse-ui.js:1:423)
    at Object.<anonymous> (/Users/vinchan/LearnPro/shufeijie_test/node_modules/muse-ui/dist/muse-ui.js:9:18415)
    at t (/Users/vinchan/LearnPro/shufeijie_test/node_modules/muse-ui/dist/muse-ui.js:1:423)

**Comment by myronliu347** [comment]
有些地方实用了 `window.`， ssr的时候没有window对象所以报错了，是我疏忽了，我稍后提交，近期发下一个版本

**Comment by BubblyPoker** [comment]
这种情况需要怎么改进呢，求指教

**Comment by arfaWong** [comment]
beta2版本依然会报这个错误 @myronliu347

**Comment by myronliu347** [comment]
@arfaWong 我还没发布，稍等

**Comment by Giina** [comment]
你好，我在使用了nuxt的项目中使用V2.0.1版本的muse-ui，同样的出现了这个问题。求助
`Nuxt.js error

ReferenceError: Element is not defined
    at Object.<anonymous> (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:9:147415)
    at e (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:6:355)
    at Object.t.exports.render.t (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:9:167813)
    at e (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:6:355)
    at Object.t.__esModule.default (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:9:10120)
    at e (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:6:355)
    at Object.defineProperty.value (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:9:79861)
    at e (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:6:355)
    at Object.<anonymous> (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:9:164233)
    at e (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:6:355)
    at Object.defineProperty.value (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:9:2440)
    at e (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:6:355)
    at Object.<anonymous> (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:9:226710)
    at e (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:6:355)
    at t.exports.t (E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:6:738)
    at E:\Project\MetaLab2\maikeji_v6_front_pc\node_modules\.2.0.1@muse-ui\dist\muse-ui.js:6:749`
