### ISSUE TITLE
vue.js:439 TypeError: Cannot set property 'isRootInsert' of undefined

### ISSUE THREAD

**Issue by saopang** [museui/muse-ui#185]
muse-ui
2.0.0-beta.3
vue
2.1.7
```
vue.js:439 TypeError: Cannot set property 'isRootInsert' of undefined
    at createElm (http://localhost:8072/assets/js/lib/vue/2.1.7/vue.js:4055:24)
    at createChildren (http://localhost:8072/assets/js/lib/vue/2.1.7/vue.js:4164:9)
    at createElm (http://localhost:8072/assets/js/lib/vue/2.1.7/vue.js:4089:9)
    at VueComponent.patch [as __patch__] (http://localhost:8072/assets/js/lib/vue/2.1.7/vue.js:4507:7)
    at VueComponent.Vue._update (http://localhost:8072/assets/js/lib/vue/2.1.7/vue.js:2483:19)
    at VueComponent.<anonymous> (http://localhost:8072/assets/js/lib/vue/2.1.7/vue.js:2457:10)
    at Watcher.get (http://localhost:8072/assets/js/lib/vue/2.1.7/vue.js:1663:27)
    at new Watcher (http://localhost:8072/assets/js/lib/vue/2.1.7/vue.js:1655:12)
    at VueComponent.Vue._mount (http://localhost:8072/assets/js/lib/vue/2.1.7/vue.js:2456:19)
    at VueComponent.Vue$3.$mount (http://localhost:8072/assets/js/lib/vue/2.1.7/vue.js:6078:15)logError @ vue.js:439
client?4fb7:38 [WDS] Hot Module Replacement enabled.
```
怀疑是vue2.1.7升级后需要用`the latest versions of vue-template-compiler and vue-template-es2015-compiler`
参见vue升级日志：https://github.com/vuejs/vue/releases
紧急bug，望大神修复，线上版本

**Comment by myronliu347** [comment]
ok，我等下升级下

**Comment by myronliu347** [comment]
昨天加班太晚，回去没上github

**Comment by myronliu347** [comment]
目前这个版本，发现改变了许多东西，建议先退回 vue 2.1.5

**Comment by saopang** [comment]
辛苦辛苦，
现在pc用的element，vue2.1.7
微信用的muse-ui，vue2.1.6，但是2.1.6有个removeNode的bug，在tab切换时会触发
期待大神的修复

**Comment by peirancao** [comment]
@myronliu347  回退不了啊 用 vue-cli 创建的项目 回退后总是提示 vue-template-compiler 版本不匹配 都会退到2.1.5了 还是提示 2.1.7点 vue-template-compiler

**Comment by myronliu347** [comment]
```
npm install vue@2.1.5 --save

npm install vue-template-compiler@2.1.5 --save-dev
```

**Comment by roslaneshellanoo** [comment]
@myronliu347 
I had this problem with the newest version of vue.js:
Cannot read property 'context' of undefined

Your solution helped me. installed vue@2.1.5 and vue-template-compiler@2.1.5 

Thanks a lot

**Comment by myronliu347** [comment]
vue发布了2.1.8版本修复了以往的问题,muse-ui 已使用最新版的vue重新编译，各位可以更新下vue和muse-ui
