### ISSUE TITLE
SSR 報錯

### ISSUE THREAD

**Issue by bluemastodon66** [museui/muse-ui#221]
不好意思，發現使用 ssr 時，會報錯。

`ReferenceError: Element is not defined
    at Object. (D:\vue\node-es2015-support-starter\node_modules\muse-ui\dist\muse-ui.js:8:28503)
    at t (D:\vue\node-es2015-support-starter\node_modules\muse-ui\dist\muse-ui.js:1:423)
    at Object.e.exports.render.e (D:\vue\node-es2015-support-starter\node_modules\muse-ui\dist\muse-ui.js:9:30701)
    at t (D:\vue\node-es2015-support-starter\node_modules\muse-ui\dist\muse-ui.js:1:423)
    at Object.defineProperty.value (D:\vue\node-es2015-support-starter\node_modules\muse-ui\dist\muse-ui.js:4:13167)
    at t (D:\vue\node-es2015-support-starter\node_modules\muse-ui\dist\muse-ui.js:1:423)
    at Object.e.__esModule.default (D:\vue\node-es2015-support-starter\node_modules\muse-ui\dist\muse-ui.js:6:20788)
    at t (D:\vue\node-es2015-support-starter\node_modules\muse-ui\dist\muse-ui.js:1:423)
    at Object. (D:\vue\node-es2015-support-starter\node_modules\muse-ui\dist\muse-ui.js:9:19711)
    at t (D:\vue\node-es2015-support-starter\node_modules\muse-ui\dist\muse-ui.js:1:423)`

我的 env node6

**Comment by myronliu347** [comment]
暂时还没有支持ssr，抱歉
