### ISSUE TITLE
Custom build fails

### ISSUE THREAD

**Issue by Dreamerpro** [museui/muse-ui#324]
I want to modify some components for my project but my custom build fails always giving error 
```
ERROR in ./src/index.js
Module parse failed: E:\Projects\Web\test-project\node_modules\muse-ui\src\index.js Unexpected token (66:2)
You may need an appropriate loader to handle this file type.
```
I am using `npm install muse-ui -save `command to install into project then I copied **build** , **conf**  and **.babelrc**  from master tree to local **node_modules/muse_ui** . node packages are installed with `npm install command`. When I try to build with `npm run build` it gives above error. 

The line 66th of `muse-ui\src\index.js` is ` ...list,` the error must be due to spread operator.  I tried to install babel plugin `babel-plugin-transform-es2015-spread` from https://babeljs.io/docs/plugins/transform-es2015-spread/  using the documentation there still getting same here. I am new to this and currently have no idea to solve this. Thanks.
.

**Comment by myronliu347** [comment]
webpack.conf.js
{
  // ...
  module: {
    loaders: [
      // ...
      {
        test: /muse-ui.src.*?js$/,
        loader: 'babel'
      }
    ]
  },
  resolve: {
    // ...
    alias: {
      'muse-components': 'muse-ui/src'
    }
  }
}

**Comment by Dreamerpro** [comment]
Hello @myronliu347 , my 'buildwebpack.base.js' is copy of  https://github.com/museui/muse-ui/blob/master/build/webpack.prod.js . When I run `npm run build` it throws error for https://github.com/museui/muse-ui/blob/master/src/index.js  file at line 66  , the spread operator. I have .babelrc file also copied from https://github.com/museui/muse-ui/blob/master/.babelrc . That contains **stage-2** preset which should solve the problem of spread operator, but still the error is being thrown.

**Comment by myronliu347** [comment]
please show error message and 'webpack.base.js' code

**Comment by Dreamerpro** [comment]
`webpack.base.js` below
```
var path = require('path')
var config = require('../config')
var utils = require('./utils')
var projectRoot = path.resolve(__dirname, '../')
module.exports = {
  entry: config.entry,
  output: {
    path: config.assetsRoot,
    publicPath: config.assetsPublicPath,
    filename: '[name].js'
  },
  resolve: {
    extensions: ['', '.js', '.vue'],
    fallback: [path.join(__dirname, '../node_modules')],
    alias: {
      'muse-ui': path.resolve(__dirname, '../src'),
      'src': path.resolve(__dirname, '../src')
    }
  },
  resolveLoader: {
    fallback: [path.join(__dirname, '../node_modules')]
  },
  module: {
    preLoaders: [
      {
        test: /\.vue$/,
        loader: 'eslint',
        include: projectRoot,
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        loader: 'eslint',
        include: projectRoot,
        exclude: /node_modules/
      }
    ],
    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.js$/,
        loader: 'babel',
        include: projectRoot,
        exclude: /node_modules/
      },
      {
        test: /\.json$/,
        loader: 'json'
      },
      {
        test: /\.html$/,
        loader: 'vue-html'
      },
      {
        test: /\.md$/,
        loader: 'raw-loader'
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url',
        query: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url',
        query: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  },
  eslint: {
    formatter: require('eslint-friendly-formatter')
  },
  vue: {
    loaders: utils.cssLoaders({ sourceMap: false }),
    postcss: [
      require('autoprefixer')({
        browsers: ['ie > 9', 'chrome > 24', 'android >= 4.2', 'ios >= 7', 'safari >= 8', 'last 10 versions']
      })
    ]
  }
}

```

Error code
```
ERROR in ./src/index.js
Module parse failed: E:\Projects\Web\testproject\node_modules\muse-ui\src\index.js Unexpected token (66:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (66:2)
    at Parser.pp$4.raise (E:\Projects\Web\testproject\node_modules\muse-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projects\Web\testproject\node_modules\muse-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseIdent (E:\Projects\Web\testproject\node_modules\muse-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2189:12)
    at Parser.pp$3.parsePropertyName (E:\Projects\Web\testproject\node_modules\muse-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2052:101)
    at Parser.pp$3.parseObj (E:\Projects\Web\testproject\node_modules\muse-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:1988:14)
    at Parser.pp$3.parseExprAtom (E:\Projects\Web\testproject\node_modules\muse-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:1805:19)
    at Parser.pp$3.parseExprSubscripts (E:\Projects\Web\testproject\node_modules\muse-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (E:\Projects\Web\testproject\node_modules\muse-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (E:\Projects\Web\testproject\node_modules\muse-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (E:\Projects\Web\testproject\node_modules\muse-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:1620:21)
[08:57:34] No gulpfile found

```

**Comment by adityaism** [comment]
I can sucessfully build clone of  master tree, but when i replace `muse-ui` folder with the built one it throws error for each component. 
```
[Vue warn]: Unknown custom element: <mu-appbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in root instance)
```

**Comment by myronliu347** [comment]
You missed

```javascript
{
     // ...
     module: {
          loaders: [
          // ...
          {
               test: /muse-ui.src.*?js$/,
               loader: 'babel'
          }
          ]
     },
     resolve: {
          // ...
          alias: {
               'muse-components': 'muse-ui/src'
          }
     }
}
```

**Comment by Dreamerpro** [comment]
getting same error ```
[Vue warn]: Unknown custom element: <mu-appbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in root instance)```

**Comment by myronliu347** [comment]
before '.js' loader
```javascript
var path = require('path')
var config = require('../config')
var utils = require('./utils')
var projectRoot = path.resolve(__dirname, '../')
module.exports = {
  entry: config.entry,
  output: {
    path: config.assetsRoot,
    publicPath: config.assetsPublicPath,
    filename: '[name].js'
  },
  resolve: {
    extensions: ['', '.js', '.vue'],
    fallback: [path.join(__dirname, '../node_modules')],
    alias: {
      'muse-ui': path.resolve(__dirname, '../src'),
      'src': path.resolve(__dirname, '../src'),
      'muse-components': 'muse-ui/src'
    }
  },
  resolveLoader: {
    fallback: [path.join(__dirname, '../node_modules')]
  },
  module: {
    preLoaders: [
      {
        test: /\.vue$/,
        loader: 'eslint',
        include: projectRoot,
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        loader: 'eslint',
        include: projectRoot,
        exclude: /node_modules/
      }
    ],
    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /muse-ui.src.*?js$/,
        loader: 'babel'
      },
{
        test: /\.js$/,
        loader: 'babel',
        include: projectRoot,
        exclude: /node_modules/
      },
      {
        test: /\.json$/,
        loader: 'json'
      },
      {
        test: /\.html$/,
        loader: 'vue-html'
      },
      {
        test: /\.md$/,
        loader: 'raw-loader'
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url',
        query: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url',
        query: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  },

  eslint: {
    formatter: require('eslint-friendly-formatter')
  },
  vue: {
    loaders: utils.cssLoaders({ sourceMap: false }),
    postcss: [
      require('autoprefixer')({
        browsers: ['ie > 9', 'chrome > 24', 'android >= 4.2', 'ios >= 7', 'safari >= 8', 'last 10 versions']
      })
    ]
  }
}
```

**Comment by Dreamerpro** [comment]
(getting closer)
I can execute `npm run build` but get this errors  if i run my project
```[Vue warn]: Unknown custom element: <mu-appbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in root instance)
warn @ vue.common.js?e881:521
createElm @ vue.common.js?e881:4135
createChildren @ vue.common.js?e881:4242
createElm @ vue.common.js?e881:4150
patch @ vue.common.js?e881:4605
Vue._update @ vue.common.js?e881:2635
updateComponent @ vue.common.js?e881:2609
get @ vue.common.js?e881:2934
Watcher @ vue.common.js?e881:2926
Vue._mount @ vue.common.js?e881:2608
Vue$3.$mount @ vue.common.js?e881:6178
Vue$3.$mount @ vue.common.js?e881:8549
(anonymous) @ main.js?3479:36
(anonymous) @ build.js:1253
__webpack_require__ @ build.js:660
fn @ build.js:84
(anonymous) @ build.js:2415
__webpack_require__ @ build.js:660
(anonymous) @ build.js:709
(anonymous) @ build.js:712
6vue.common.js?e881:521 [Vue warn]: Unknown custom element: <mu-icon-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in root instance)
warn @ vue.common.js?e881:521
createElm @ vue.common.js?e881:4135
createChildren @ vue.common.js?e881:4242
createElm @ vue.common.js?e881:4150
createChildren @ vue.common.js?e881:4242
createElm @ vue.common.js?e881:4150
patch @ vue.common.js?e881:4605
Vue._update @ vue.common.js?e881:2635
updateComponent @ vue.common.js?e881:2609
get @ vue.common.js?e881:2934
Watcher @ vue.common.js?e881:2926
Vue._mount @ vue.common.js?e881:2608
Vue$3.$mount @ vue.common.js?e881:6178
Vue$3.$mount @ vue.common.js?e881:8549
(anonymous) @ main.js?3479:36
(anonymous) @ build.js:1253
__webpack_require__ @ build.js:660
fn @ build.js:84
(anonymous) @ build.js:2415
__webpack_require__ @ build.js:660
(anonymous) @ build.js:709
(anonymous) @ build.js:712
4vue.common.js?e881:521 [Vue warn]: Unknown custom element: <mu-flat-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in root instance)
warn @ vue.common.js?e881:521
createElm @ vue.common.js?e881:4135
createChildren @ vue.common.js?e881:4242
createElm @ vue.common.js?e881:4150
createChildren @ vue.common.js?e881:4242
createElm @ vue.common.js?e881:4150
patch @ vue.common.js?e881:4605
Vue._update @ vue.common.js?e881:2635
updateComponent @ vue.common.js?e881:2609
get @ vue.common.js?e881:2934
Watcher @ vue.common.js?e881:2926
Vue._mount @ vue.common.js?e881:2608
Vue$3.$mount @ vue.common.js?e881:6178
Vue$3.$mount @ vue.common.js?e881:8549
(anonymous) @ main.js?3479:36
(anonymous) @ build.js:1253
__webpack_require__ @ build.js:660
fn @ build.js:84
(anonymous) @ build.js:2415
__webpack_require__ @ build.js:660
(anonymous) @ build.js:709
(anonymous) @ build.js:712
vue.common.js?e881:521 [Vue warn]: Unknown custom element: <mu-drawer> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in root instance)
warn @ vue.common.js?e881:521
createElm @ vue.common.js?e881:4135
createChildren @ vue.common.js?e881:4242
createElm @ vue.common.js?e881:4150
patch @ vue.common.js?e881:4605
Vue._update @ vue.common.js?e881:2635
updateComponent @ vue.common.js?e881:2609
get @ vue.common.js?e881:2934
Watcher @ vue.common.js?e881:2926
Vue._mount @ vue.common.js?e881:2608
Vue$3.$mount @ vue.common.js?e881:6178
Vue$3.$mount @ vue.common.js?e881:8549
(anonymous) @ main.js?3479:36
(anonymous) @ build.js:1253
__webpack_require__ @ build.js:660
fn @ build.js:84
(anonymous) @ build.js:2415
__webpack_require__ @ build.js:660
(anonymous) @ build.js:709
(anonymous) @ build.js:712
vue.common.js?e881:521 [Vue warn]: Unknown custom element: <mu-appbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in root instance)...
```
This problem doesn't show if i use fresh copy of `muse-ui`.

**Comment by myronliu347** [comment]
Please show  you use 'muse-ui' code

**Comment by myronliu347** [comment]
This is my project ?

**Comment by Dreamerpro** [comment]
Yes,  this is your project. You asked for 'muse-ui'  code . I am trying to modify some elements to use it in my project.
