### ISSUE TITLE
2.0.3 还是出现ssr报错信息

### ISSUE THREAD

**Issue by brandonxiang** [museui/muse-ui#531]
使用muse2.0.3出现报错信息：

```
ReferenceError: window is not defined
    at VueComponent.default (/Users/brandonxiang/github/example-vue-ssr/node_modules/muse-ui/dist/muse-ui.js:9:16863)
    at getPropDefaultValue (/Users/brandonxiang/github/example-vue-ssr/node_modules/vue/dist/vue.runtime.common.js:1425:11)
```

我使用的是类vue-hacknews2.0的项目结构。

**Comment by myronliu347** [comment]
fixed
